### PR TITLE
Mutlitests for tfi pair

### LINKED ISSUE #10: Add multitest for tfi-factory / tf-pair
Understand how we use these with cw20-base and test they work, with `multi-test` framework.

A very basic test was added to `tfi-pair`, please extend that to cover the basic use cases, only tif-pair and the issues `cw20-base` tokens.

After that some tests combining `tfi-factory` and `tfi-pair` full stack would be useful. They don't need to worry so much about the pair-token dynamics as the factory-pair ones (and one full-stack happy path sanity check)

Note: these will be extended later to test with the dso-token, so you may want to design for that extensibility (see #9)

### PR DESCRIPTION
**Pull request by hashedone**
Closes #10

### CODE REVIEW

**Review by ethanfrey — APPROVED** [review]
Good stuff.

All my comments are aesthetic - how to format code, adding comments, etc. The code itself looks quite good and nice to see you could use the cw20 send pattern and cover all these cases :+1:

Feel free to merge this when you addressed the comments that make sense to you.

Also, it seems like bumping to cosmwasm-plus rc2 would be helpful for the newer APIs, so please do that next.

**Review by ethanfrey — APPROVED** [review]
One more thought after seeing the linter errors

**Review by maurolacy — COMMENTED** [review]
Thanks for the examples. Trying to wrap my head around it. Need a reference to better understand this.

**Review by ethanfrey — APPROVED** [review]
Nice Suite refactoring.

A few suggestions you might want to consider as you add more tests, but in general, this looks very nice.

I note you chain the assertions, but I rarely see you chaining the actions, so maybe it would be useful to return some other info (eg. AppResponse)

**Pull request merged**
