### PR TITLE
Redeem implementation for dso-token

### PR DESCRIPTION
**Pull request by hashedone**
Still draft, as test are to be written (working on this right now, just wanted to expose what is done already).

### CODE REVIEW

**Review by ethanfrey — COMMENTED** [review]
Looks like a nice design and thanks for saving redeems to query them.

it would be nice to add some way to clean them up.

I will review the contract.rs code later

**Review by maurolacy — COMMENTED** [review]
Looks good. Thanks for adding the detailed docs.

Please `s/\([rR]\)eedem/\1edeem/g` everywhere. I don't want to be annoying, but if you don't mind I can proof read the docs, etc. and suggest edits.

**Review by ethanfrey — COMMENTED** [review]
a few more comments.

let me know when you push all changes and I will go through for last approval

**Review by ethanfrey — APPROVED** [review]
Looks good. 
A few stylistic comments, but the logic seems good and the tests nice.

I would add one more test to cover some failure cases where you cannot redeem

**Pull request merged**
